language: node_js
node_js: 6.11.0

install:
  - npm i

script:
  - npm run test

cache:
  enabled: true
  directories:
  - ./node_modules

deploy:
  - branch: "production"
    shell:
      - "DEPLOY_TO=humaniq-production OVERRIDE_VALUES=values.yaml ZONE=europe-west1-b ./scripts/deploy.sh"
  - branch: "development"
    shell:
      - "DEPLOY_TO=pre-staging OVERRIDE_VALUES=values-dev.yaml ZONE=europe-west1-b ./scripts/deploy_new.sh"
