language: node_js
node_js: 6.11.0

install:
  - npm i
  - npm run build
script:
  - npm run test

cache:
  enabled: true
  directories:
  - ./node_modules

deploy:
  shell:
    - "./deploy.sh"
  branch: deploy
