export const REQUEST = 'REQUEST_'
export const OPEN = 'OPEN_'
export const TOGGLE = 'TOGGLE_'
export const FETCH = 'FETCH_'
export const CLOSE = 'CLOSE_'
export const SET = 'SET_'
export const CLEAN = 'CLEAN_'

export const BLOCKCHAIN_TRANSACTIONS = 'BLOCKCHAIN_TRANSACTIONS'
export const HMQ_STATISTICS = 'HMQ_STATISTICS'
export const HMQ_MARKETS = 'HMQ_MARKETS'
export const HMQ_HOLDERS = 'HMQ_HOLDERS'
export const HMQ_HOLDER = 'HMQ_HOLDER'
export const HMQ_HOLDER_T = 'HMQ_HOLDER_T'
export const HMQ_LOG = 'HMQ_LOG'
export const HMQ_SECTION = 'HMQ_SECTION'
export const HMQ_BLOCK = 'HMQ_BLOCK'
export const HMQ_GRAPH = 'HMQ_GRAPH'
export const HMQ_HASH = 'HMQ_HASH'
export const HMQ_SEARCH = 'HMQ_SEARCH'

export const THEME = 'THEME'
export const OPEN_ROUTE = 'OPEN_ROUTE'
export const POST = 'POST'
export const POPUP = 'POPUP'
export const POSTS = 'POSTS'
export const ERROR = 'ERROR'
export const MENU = 'MENU'
export const PARTNERS = 'PARTNERS'
export const AMBASSADORS = 'AMBASSADORS'
export const BY_REFERENCE = 'BY_REFERENCE'

export const CONTENT = 'CONTENT'
export const STATIC_DATA = 'STATIC_DATA'
export const WIKI = 'WIKI'
export const WIKI_SEARCH = 'WIKI_SEARCH'

export const JOIN_FORM = 'JOIN_FORM'
export const SUBSCRIBE_FORM = 'SUBSCRIBE_FORM'
export const AMBASSADORS_FORM = 'AMBASSADORS_FORM'

export const START = '_START'
export const SUCCESS = '_SUCCESS'
export const FAIL = '_FAIL'